server:
  port: 9000

spring:
  cloud:
    gateway:
      routes:
        - id: monolith-simple-mall
          uri: http://localhost:${upstream.monolith.port}/
          predicates:
            - Path=/v1/**

upstream:
  monolith:
    port: 8080
