server:
  tomcat:
    threads:
      max: 1

spring.jpa.hibernate.ddl-auto: create

spring.datasource:
  url: jdbc:mysql://localhost:3306/monolith-simple-mall
  username: user
  password: pwd

spring:
  application:
    name: monolith-simple-mall
  cloud:
    consul:
      discovery:
        instance-id: ${spring.application.name}.${random.value}
    loadbalancer:
      ribbon:
        enabled: false
  jpa:
    show-sql: true
    open-in-view: false

springdoc:
  swagger-ui:
    url: https://gist.githubusercontent.com/HomoEfficio/d36c556dc6fe0e5cbe2b0cee81dadbb6/raw/acbb69b74529e8c254296285ba7be748f5e66cd6/open-api-3-for-msa-simple-mall.yaml

logging:
  level:
    io.homo_efficio: DEBUG

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
  endpoint:
    health:
      show-details: always



---
spring.profiles: open-api-gen

server:
  port: 8080
  ssl:
    enabled: false



---
spring.profiles: docker

server:
  tomcat:
    threads:
      max: 200

spring:
  jpa:
    show-sql: false
